[package]
name = "lantir_render"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
lantir_hal = { path = "../lantir_hal" }
glam = "0.30.10"
anyhow = "1.0.100"
parking_lot = "0.12.5"
image = { version = "0.25.6", default-features = false, features = [
    "png",
    "jpeg",
] }
bevy_app = "0.18.0"
bevy_window = "0.18.0"
bevy_winit = "0.18.0"
bevy_ecs = { version = "0.18.0", features = ["debug"] }
bevy_transform = "0.18.0"

[build-dependencies]
