[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
lantir_render = { path = "../crates/lantir_render" }
lantir_hal = { path = "../crates/lantir_hal" }
lantir_gltf = { path = "../crates/lantir_gltf" }
lantir_bevy = { path = "../crates/lantir_bevy" }

bevy_app = "0.18.0"
bevy_ecs = { version = "0.18.0", features = ["debug"] }
bevy_input = "0.18.0"
bevy_a11y = "0.18.0"
bevy_window = "0.18.0"
bevy_winit = "0.18.0"
bevy_time = "0.18.0"
bevy_transform = "0.18.0"
bevy_scene = "0.18.0"

avian3d = { version = "0.5", default-features = false, features = [
    "3d",
    "f32",
    "parry-f32",
] }

winit = { version = "0.30", features = ["rwh_06"] }
anyhow = "1.0.100"
gltf = "1.4.1"
image = { version = "0.25.6", default-features = false, features = [
    "png",
    "jpeg",
] }
glam = "0.30.10"
