[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
lantir_render = { path = "../crates/lantir_render" }
lantir_hal = { path = "../crates/lantir_hal" }
lantir_gltf = { path = "../crates/lantir_gltf" }

bevy_app = "0.15.3"
bevy_ecs = "0.15.3"
bevy_input = "0.15.3"
bevy_a11y = "0.15.3"
bevy_window = "0.15.3"
bevy_winit = "0.15.3"

winit = { version = "0.30", features = ["rwh_06"] }
anyhow = "1.0.100"
gltf = "1.4.1"
image = { version = "0.25.6", default-features = false, features = ["png", "jpeg"] }
glam = "0.30.10"

